### ISSUE TITLE
Variable declaration is wrong

### ISSUE THREAD

**Issue by JuhaJGamer** [KernelDeimos/boi-lang#2]
Variables should be declared as ONE [name] BOI

**Comment by KernelDeimos** [comment]
You're absolutely right - I'll have this issue fixed asap

**Comment by KernelDeimos** [comment]
This has been fixed now!

Since was a severe issue affecting the language, I updated the binaries as well. I also made `BOI` an acceptable statement terminator so that the declaration can be done in all caps, as this can be important as well.

Thanks again for reporting this
